name: afguide
channels:
  - defaults
dependencies:
  - python=3.6
  - pip
  - six=1.16.0
  - tqdm
  - pip:
    - click==8.0.4
    - cloudpickle==1.6.0
    - dm-control
    - gym==0.18.0
    - h5py==3.1.0
    - imageio==2.9.0
    - matplotlib==3.3.4
    - mujoco-py
    - networkx==2.5.1
    - omegaconf==2.2.2
    - pandas==1.1.5
    - pybullet==3.2.5
    - pyopengl==3.1.6
    - pyyaml==6.0
    - stable-baselines3==1.3.0
    - torch==1.10.2
    - torchvision
    - urllib3==1.26.11
    - wandb
    - -e git+https://github.com/aravindr93/mjrl.git#egg=mjrl
