wandb:
  project: "AF-Guide"
  group: "hopper_medium_replay"
  entity: null  # write yours
  mode: "online"  # set to online, if needed

dataset:
  env_name: "hopper-medium-replay-v2"

model:
  type: "afdt"
  planner_path: "pretrained_acdt/acdt_hopper_medium_replay.pt"
  observation_dim: 11
  action_dim: 3
  embedding_dim: 128
  context_len: 20
  num_layers: 3
  num_heads: 1
  rtg_target: 3600
  rtg_scale: 1000

trainer:
  coe_int_r: 0
  coe_env_r: 1
  lr: 6e-4
  betas: [ 0.9, 0.95 ]
  weight_decay: 0.1
  clip_grad: 1.0
  step_warm: 0
  eval_seed: 42
  eval_every: 10000
  eval_episodes: 5
  train_every: 5
  num_steps: 1000000
  checkpoints_root: "checkpoints/${dataset.env_name}"
  name_prefix: "sac"